### ISSUE TITLE
Bazel 7.0 will require rules_proto_grpc to be > 1.60.0

### ISSUE THREAD

**Issue by Ryang20718** [rules-proto-grpc/rules_proto_grpc#305] opened 2023-12-29 01:07 UTC
### Description

https://github.com/rules-proto-grpc/rules_proto_grpc/blob/7afd2ddadd6113b65787786653b00cf0cb29f1e7/modules/python/MODULE.bazel#L7

Depends on https://github.com/rules-proto-grpc/rules_proto_grpc/issues/304

**Comment by aaliddell** [comment] 2023-12-29 23:50
Dupe of #304

**Closed by aaliddell** 2023-12-29 23:50 UTC
Labels: duplicate
